FROM ghcr.io/rocker-org/devcontainer/r-ver:4.5

# Architecture-specific variable (built in Docker BuildKit)
ARG TARGETARCH

# Runtime dependency for R package 'fs' (provides libuv.so.1)
RUN apt-get update && \
    apt-get install -y --no-install-recommends libuv1t64 && \
    rm -rf /var/lib/apt/lists/*

# Install quarto-cli and the orange-book extension
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.35/quarto-1.9.35-linux-${TARGETARCH}.deb && \
    dpkg -i quarto-1.9.35-linux-${TARGETARCH}.deb && \
    rm quarto-1.9.35-linux-${TARGETARCH}.deb

# Adding R packages
RUN install2.r --error fable \
    fabletools \
    progressr \
    feasts \
    tsibble \
    dplyr \
    tidyr \
    ggplot2 \
    distributional \
    epidatr \
    rlang \
    EpiEstim \
    projections \
    incidence \
    jsonlite \
    baselinenowcast \
    DiagrammeR \
    knitr \
    rmarkdown \
    devtools \
    pipetime \
    fable.prophet \
    testthat

RUN installGithub.r hubverse-org/hubEvals

CMD ["bash"]
